// <auto-generated />
using System;
using System.Collections.Generic;
using GymBook.LocalData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymBook.LocalData.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20261002061842_SkippedSets")]
    partial class SkippedSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GymBook.LocalData.LocalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.BodyWeightEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("BmrKcal")
                        .HasColumnType("REAL");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("BodyWaterKg")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoneMassKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LeanMassKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("body_weights", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mechanic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryMuscle")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("custom_exercises", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.FoodEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsG")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FatG")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Meal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinG")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("food_entries", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.HealthDay", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ActiveBurnedKcal")
                        .HasColumnType("REAL");

                    b.Property<double?>("BasalBurnedKcal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FoodCarbsG")
                        .HasColumnType("REAL");

                    b.Property<double?>("FoodFatG")
                        .HasColumnType("REAL");

                    b.Property<double?>("FoodKcal")
                        .HasColumnType("REAL");

                    b.Property<double?>("FoodProteinG")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalBurnedKcal")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("health_days", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.UserProfile", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivePlanId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRestTimer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("BodyWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int?>("CalorieGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarbsGoalG")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompoundRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultDeloads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultPeriodization")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnergyBalanceGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FatGoalG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthSource")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<bool>("ImportHealthFood")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IsolationRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnboardingDone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProteinGoalG")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackRir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrainNeck")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TrainingSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarmupRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WarmupSuggestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warmups")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.WorkoutPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompoundRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IsolationRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextWorkoutIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OwnRest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OwnTraining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Periodization")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RestDays")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RestDaysDone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetRir")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseRir")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WarmupRestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warmups")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Workouts", "GymBook.Models.WorkoutPlan.Workouts#PlanWorkout", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Id")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Exercises", "GymBook.Models.WorkoutPlan.Workouts#PlanWorkout.Exercises#PlanExercise", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("CustomRest");

                                    b2.Property<bool>("CustomRir");

                                    b2.Property<bool?>("Deloads");

                                    b2.Property<string>("ExerciseId")
                                        .IsRequired();

                                    b2.Property<string>("Note");

                                    b2.Property<bool?>("Periodization");

                                    b2.Property<int>("RepMax");

                                    b2.Property<int>("RepMin");

                                    b2.Property<int>("RestSeconds");

                                    b2.Property<int>("Sets");

                                    b2.Property<int>("TargetRir");

                                    b2.Property<string>("Warmups");
                                });

                            b1
                                .ToJson("Workouts")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.WorkoutSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dirty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanWorkoutId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Exercises", "GymBook.Models.WorkoutSession.Exercises#SessionExercise", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ExerciseId")
                                .IsRequired();

                            b1.Property<string>("Note");

                            b1.Property<bool>("NotePinned");

                            b1.Property<string>("Recommendation");

                            b1.Property<int>("RepMax");

                            b1.Property<int>("RepMin");

                            b1.Property<int>("RestSeconds");

                            b1.Property<int>("SkippedSets");

                            b1.Property<int>("SkippedWarmups");

                            b1.Property<int>("TargetRir");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sets", "GymBook.Models.WorkoutSession.Exercises#SessionExercise.Sets#SetEntry", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateTime?>("CompletedAt");

                                    b2.Property<bool>("IsCompleted");

                                    b2.Property<bool>("IsSkipped");

                                    b2.Property<bool>("IsWarmup");

                                    b2.Property<int>("Reps");

                                    b2.Property<DateTime?>("RestEndedAt");

                                    b2.Property<DateTime?>("RestStartedAt");

                                    b2.Property<int?>("Rir");

                                    b2.Property<DateTime?>("StartedAt");

                                    b2.Property<double>("WeightKg");
                                });

                            b1
                                .ToJson("Exercises")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
