// <auto-generated />
using System;
using System.Collections.Generic;
using GymBook.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymBook.Api.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20261006090000_Social")]
    partial class Social
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymBook.Api.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AdminRole")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<long>("SyncVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind", "CreatedAt");

                    b.ToTable("plan_generations", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.Avatar", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserId");

                    b.ToTable("avatars", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.Friendship", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("FriendId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanShare", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("AllowCopy")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PlanId")
                        .IsUnique();

                    b.ToTable("plan_shares", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanShareMembership", b =>
                {
                    b.Property<string>("ShareId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ShareId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("plan_share_members", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.RankReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Lift")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId", "TargetId");

                    b.HasIndex("TargetId", "ResolvedAt");

                    b.ToTable("rank_reports", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.RankedLift", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Lift")
                        .HasColumnType("integer");

                    b.Property<double>("BodyWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("E1RmKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("Ranked")
                        .HasColumnType("boolean");

                    b.Property<double>("Ratio")
                        .HasColumnType("double precision");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "Lift");

                    b.HasIndex("Lift", "Score");

                    b.ToTable("ranked_lifts", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.SocialProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("AvatarVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("HomeGym")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("InRanks")
                        .HasColumnType("boolean");

                    b.Property<bool>("RankHidden")
                        .HasColumnType("boolean");

                    b.Property<int?>("RankSex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RanksUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsernameKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.HasIndex("FriendCode")
                        .IsUnique();

                    b.HasIndex("UsernameKey")
                        .IsUnique();

                    b.HasIndex("InRanks", "RankHidden", "Score");

                    b.ToTable("social_profiles", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.BodyWeightEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("BmrKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("BodyWaterKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("BoneMassKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("LeanMassKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("body_weights", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.Exercise", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Equipment")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Mechanic")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscle")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("custom_exercises", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.FoodEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Meal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("food_entries", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.HealthDay", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("ActiveBurnedKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("BasalBurnedKcal")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("FoodCarbsG")
                        .HasColumnType("double precision");

                    b.Property<double?>("FoodFatG")
                        .HasColumnType("double precision");

                    b.Property<double?>("FoodKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("FoodProteinG")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SleepMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalBurnedKcal")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("health_days", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.SupplementDose", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Grams")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("supplement_doses", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ActivePlanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRestTimer")
                        .HasColumnType("boolean");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<double?>("BodyFatPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("BodyWeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("CalorieGoal")
                        .HasColumnType("integer");

                    b.Property<int?>("CarbsGoalG")
                        .HasColumnType("integer");

                    b.Property<int?>("CompoundRestSeconds")
                        .HasColumnType("integer");

                    b.Property<double>("CreatineDoseG")
                        .HasColumnType("double precision");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultDeloads")
                        .HasColumnType("boolean");

                    b.Property<bool>("DefaultPeriodization")
                        .HasColumnType("boolean");

                    b.Property<int?>("EnergyBalanceGoal")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentAccess")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int?>("FatGoalG")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("HealthApps")
                        .HasColumnType("text[]");

                    b.Property<int>("HealthSource")
                        .HasColumnType("integer");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("ImportHealthFood")
                        .HasColumnType("boolean");

                    b.Property<int?>("IsolationRestSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OnboardingDone")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProteinGoalG")
                        .HasColumnType("integer");

                    b.Property<int>("SessionMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.Property<bool>("TrackRir")
                        .HasColumnType("boolean");

                    b.Property<bool>("TrainNeck")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TrainingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int>("WarmupRestSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("WarmupSuggestions")
                        .HasColumnType("boolean");

                    b.Property<string>("Warmups")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "MyFoods", "GymBook.Models.UserProfile.MyFoods#SavedFood", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Brand");

                            b1.Property<double>("Calories");

                            b1.Property<double>("CarbsG");

                            b1.Property<double>("FatG");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<double>("ProteinG");

                            b1.Property<double?>("ServingG");

                            b1.Property<string>("ServingText");

                            b1
                                .ToJson("MyFoods")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("UserId");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.WorkoutPlan", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("CompoundRestSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("Deloads")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("IsolationRestSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NextWorkoutIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("OwnRest")
                        .HasColumnType("boolean");

                    b.Property<bool>("OwnTraining")
                        .HasColumnType("boolean");

                    b.Property<bool>("Periodization")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<int>>("RestDays")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("RestDaysDone")
                        .HasColumnType("integer[]");

                    b.Property<string>("ShareId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ShareRole")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRir")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseRir")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WarmupRestSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Warmups")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Workouts", "GymBook.Models.WorkoutPlan.Workouts#PlanWorkout", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Id")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Exercises", "GymBook.Models.WorkoutPlan.Workouts#PlanWorkout.Exercises#PlanExercise", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool>("CustomRest");

                                    b2.Property<bool>("CustomRir");

                                    b2.Property<bool?>("Deloads");

                                    b2.Property<string>("ExerciseId")
                                        .IsRequired();

                                    b2.Property<string>("Note");

                                    b2.Property<bool?>("Periodization");

                                    b2.Property<int>("RepMax");

                                    b2.Property<int>("RepMin");

                                    b2.Property<int>("RestSeconds");

                                    b2.Property<int>("Sets");

                                    b2.Property<int>("TargetRir");

                                    b2.Property<string>("Warmups");
                                });

                            b1
                                .ToJson("Workouts")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("GymBook.Models.WorkoutSession", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PlanId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlanWeek")
                        .HasColumnType("integer");

                    b.Property<string>("PlanWorkoutId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ReopenedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Exercises", "GymBook.Models.WorkoutSession.Exercises#SessionExercise", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ExerciseId")
                                .IsRequired();

                            b1.Property<string>("Note");

                            b1.Property<bool>("NotePinned");

                            b1.Property<string>("Recommendation");

                            b1.Property<int>("RepMax");

                            b1.Property<int>("RepMin");

                            b1.Property<int>("RestSeconds");

                            b1.Property<int>("SkippedSets");

                            b1.Property<int>("SkippedWarmups");

                            b1.Property<int>("TargetRir");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sets", "GymBook.Models.WorkoutSession.Exercises#SessionExercise.Sets#SetEntry", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateTime?>("CompletedAt");

                                    b2.Property<bool>("IsCompleted");

                                    b2.Property<bool>("IsSkipped");

                                    b2.Property<bool>("IsWarmup");

                                    b2.Property<int>("Reps");

                                    b2.Property<DateTime?>("RestDueAt");

                                    b2.Property<DateTime?>("RestEndedAt");

                                    b2.Property<DateTime?>("RestStartedAt");

                                    b2.Property<int?>("Rir");

                                    b2.Property<DateTime?>("StartedAt");

                                    b2.Property<double>("WeightKg");
                                });

                            b1
                                .ToJson("Exercises")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Version");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanGeneration", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.RefreshToken", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.Avatar", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithOne()
                        .HasForeignKey("GymBook.Api.Data.Avatar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.Friendship", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanShare", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.PlanShareMembership", b =>
                {
                    b.HasOne("GymBook.Api.Data.PlanShare", null)
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.RankReport", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.RankedLift", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Api.Data.SocialProfile", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithOne()
                        .HasForeignKey("GymBook.Api.Data.SocialProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.BodyWeightEntry", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.Exercise", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.FoodEntry", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.HealthDay", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.SupplementDose", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.UserProfile", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.WorkoutPlan", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBook.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymBook.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
