-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcJfy4sYlUeNF3fYi
EWpd775aet6doCH6QCMPxnrlKKigCgYIKoZIzj0DAQehRANCAASZmqmxCOwTgm5U
DyHYymMsZmMENiBqSk7pVsjuL3iOCnan3IYOKY8Na4/89J0dt6b/rWuIel7LBwnl
YdPTOwlN
-----END PRIVATE KEY-----